apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: limes-ci-pvc
  namespace: arc-runners
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti  # models (Qwen3.5-35B ~70GB) + datasets
  storageClassName: shared-wekafs
